import Head from "next/head";
import { useLazyLoadQuery } from 'react-relay/hooks';
import { graphql } from 'relay-runtime';
import type { pagesQuery as PagesQueryType } from '../__generated__/pagesQuery.graphql';

const pagesQuery = graphql`
  query pagesQuery {
    products {
      id
      name
      description
      price
      variants {
        id
        size
        color
        stock
      }
    }
  }
`;

export default function Home() {
  const data = useLazyLoadQuery<PagesQueryType>(pagesQuery, {});

  return (
    <>
      <Head>
        <title>Product Page</title>
        <meta name="description" content="Product page generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-5">
        <main>
          {data.products?.map((product) => (
            product && (
              <div key={product.id} className="product">
                <h1 className="display-4">{product.name}</h1>
                <p className="lead">{product.description}</p>
                <p className="h5">Price: ${product.price}</p>
                <h2 className="mt-4">Variants</h2>
                <ul className="list-group">
                  {product.variants.map((variant) => (
                    <li key={variant.id} className="list-group-item">
                      Size: {variant.size}, Color: {variant.color}, Stock: {variant.stock}
                    </li>
                  ))}
                </ul>
              </div>
            )
          ))}
        </main>
      </div>
    </>
  );
}
