---
- name: Gather facts for all hosts
  hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

- name: Dump all hosts' facts to a file on localhost
  hosts: all:localhost
  gather_facts: false
  tags: [facts]
  tasks:
    - name: Save facts to file on the localhost
      delegate_to: localhost
      run_once: true
      ansible.builtin.copy:
        content: "{{ hostvars | to_nice_json }}"
        dest: "/Users/igutek/tmp/all_hosts_facts.json"
      when: inventory_hostname == groups['all'][0]

- name: Local Development
  hosts: localhost
  tags: [dev, local]
  tasks:
    - name: Run Locally
      ansible.builtin.include_role:
        name: run_locally

- name: Web Servers
  hosts: web
  tags: [remote, staging]
  tasks:
    - name: Setup Web servers
      ansible.builtin.include_role:
        name: deploy_site

- name: Staging Ingress
  hosts: ingress
  tags: [remote, staging, ingress]
  tasks:
    - name: Setup Staging Load Balancer
      ansible.builtin.include_role:
        name: setup_staging_load_balancer
